###
# filename: BinaryHeapTester.py.py
# purpose:
# author:   Dr. Johnson
# date:     2023-
###

from BinaryHeap import BinaryHeap

def main():
   print( "\n\n   Binary Heap Tester\n\n" )
   print( "   Creating a new empty heap..." )
   bh = BinaryHeap()
   print( "   Inserting nodes in order: 50, 25, 30, 40, 35, 45, 99" )
   bh.insert( 50 )
   bh.insert( 25 )
   bh.insert( 30 )
   bh.insert( 40 )
   bh.insert( 35 )
   bh.insert( 45 )
   bh.insert( 99 )
   print( "   Current status is: ", end = "" )
   bh.print_heap()
   print( "\n\n   Now deleting one item:" )
   returned = bh.delete()
   print( "      Deleted item is: ", returned.get_data() )
   print( "   Current status is: ", end = "" )
   bh.print_heap()
   print( "\n\n   Inserting more nodes in order: 70, 83, 61" )
   bh.insert( 70 )
   bh.insert( 83 )
   bh.insert( 61 )
   print( "   Current status is: ", end = "" )
   bh.print_heap()
   print( "\n\n   Now deleting one item:" )
   returned = bh.delete()
   print( "      Deleted item is: ", returned.get_data() )
   print( "   Current status is: ", end = "" )
   bh.print_heap()
   print( "   Now deleting one more item:" )
   returned = bh.delete()
   print( "      Deleted item is: ", returned.get_data() )
   print( "   Current status is: ", end = "" )
   bh.print_heap()
   print( "   Now deleting one more item:" )
   returned = bh.delete()
   print( "      Deleted item is: ", returned.get_data() )
   print( "   Current status is: ", end = "" )
   bh.print_heap()
   print( "   Now deleting three more items:" )
   returned = bh.delete()
   print( "      Deleted item is: ", returned.get_data() )
   returned = bh.delete()
   print( "      Deleted item is: ", returned.get_data() )
   returned = bh.delete()
   print( "      Deleted item is: ", returned.get_data() )
   print( "   Current status is: ", end = "" )
   bh.print_heap()

   print( "   \n\n\nCreating a new empty heap..." )
   bh = BinaryHeap()
   print( "   Inserting nodes in order: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10" )
   bh.insert(  1 )
   bh.insert(  2 )
   bh.insert(  3 )
   bh.insert(  4 )
   bh.insert(  5 )
   bh.insert(  6 )
   bh.insert(  7 )
   bh.insert(  8 )
   bh.insert(  9 )
   bh.insert( 10 )
   print( "   Current status is: ", end = "" )
   bh.print_heap()
   print( "\n\n   Inserting more nodes in order: 20, 21, 22, 23, 24, 25" )
   bh.insert( 20 )
   bh.insert( 21 )
   bh.insert( 22 )
   bh.insert( 23 )
   bh.insert( 24 )
   bh.insert( 25 )
   print( "   Current status is: ", end = "" )
   bh.print_heap()
   print( "\n\n   Now deleting one item:" )
   returned = bh.delete()
   print( "      Deleted item is: ", returned.get_data() )
   print( "   Current status is: ", end = "" )
   bh.print_heap()
   print( "   Now deleting one more item:" )
   returned = bh.delete()
   print( "      Deleted item is: ", returned.get_data() )
   print( "   Current status is: ", end = "" )
   bh.print_heap()
   print( "   Now deleting one more item:" )
   returned = bh.delete()
   print( "      Deleted item is: ", returned.get_data() )
   print( "   Current status is: ", end = "" )
   bh.print_heap()
   print( "   Now deleting three more items:" )
   returned = bh.delete()
   print( "      Deleted item is: ", returned.get_data() )
   returned = bh.delete()
   print( "      Deleted item is: ", returned.get_data() )
   returned = bh.delete()
   print( "      Deleted item is: ", returned.get_data() )
   print( "   Current status is: ", end = "" )
   bh.print_heap()

   print( "\n" )

main()
